BOSSBAR:
  TITLE: "&6&LRAID EVENT &7- &cPOINTS &8» &c%block_health%"
  COLOR: "BLUE"
  STYLE: "SOLID"

BLOCK:
  NAME: "&6&lRAID EVENT"
  HEALTH: 20
  TYPE: GOLD_BLOCK
  PARTICLE: HEART
  SOUND: ENTITY_PLAYER_HURT
  LOCATION:
    X: 0
    Y: 0
    Z: 0
    YAW: 0
    PITCH: 0
    WORLD: world

MOB:
  SPAWN-TASK: 120